
@BASE_URL = http://localhost:8000/api

### ทดสอบระบบสมัครสมาชิก (Register)
POST {{BASE_URL}}/auth/register
Content-Type: application/json

{
  "email": "m.naja@example.com",
  "password": "123456",
  "name": "Mon",
  "gender": "Male"
}

### ทดสอบเข้าสู่ระบบ (Login)
POST {{BASE_URL}}/auth/login
Content-Type: application/json

{
  "email": "m.naja@example.com",
  "password": "123456"
}

### ทดสอบดูโปรไฟล์ตัวเอง (แบบไม่มี Token - ต้อง Error)
GET {{BASE_URL}}/auth/me

### ทดสอบดูโปรไฟล์ตัวเอง (แบบมี Token)
GET {{BASE_URL}}/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImE1ZTZiY2EyLTM2NWYtNDQwZS1hN2I0LWNjYjE1OWIzZjI2YSIsImVtYWlsIjoibS5uYWphQGV4YW1wbGUuY29tIiwiaWF0IjoxNzc0MzM3MjQ5LCJleHAiOjE3NzQ5NDIwNDl9.7nv7lTvHq0TmjSV-BB5jhHstTsWhauSh4wrDIEKG450


### ทดสอบอัปเดตข้อมูลสุขภาพ
PUT {{BASE_URL}}/user/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImE1ZTZiY2EyLTM2NWYtNDQwZS1hN2I0LWNjYjE1OWIzZjI2YSIsImVtYWlsIjoibS5uYWphQGV4YW1wbGUuY29tIiwiaWF0IjoxNzc0MzM3MjQ5LCJleHAiOjE3NzQ5NDIwNDl9.7nv7lTvHq0TmjSV-BB5jhHstTsWhauSh4wrDIEKG450
Content-Type: application/json

{
  "weight": 70.5,
  "height": 175,
  "bio": "ชอบเตะบอล",
  "medicalNotes": "แพ้อาหารทะเล"
}